env: "local"
http:
  port: 8001
  timeout: 5m
jwt:
  secret: "my-32-character-ultra-secure-and-ultra-long-secret"
  expiry: 30m
database:
  host: "event-db"
  user: "event"
  password: "event"
  name: "event"
  port: 5433
cache:
  prefix: "event"
  port: "6379"
  host: "keydb"
  password: "auth"
  index: 1

